phyrozz/PUPSRC-OTMS

otms_db.sql
student/administrative/generate-letter.php
student/administrative/generate-slip.php
student/administrative/request-equip.php
student/administrative/request-facility.php
student/administrative/stylesheets/slip.css

fix fetch data from request forms to generated pdf, updated tables for adminsitrative

fix fetch data to  generated pdf

---

client/registrar.php
client/registrar/create_request.php
client/registrar/index.php
client/registrar/registrar_history.php
client/registrar/your_transaction.php

- registrar, fixed sorting of data table, disabled sunday on calendar
- fixed navbar on client, pup logo should be clickable to redirect to home page, remove template navbar from registrar
- removed usage
- fixed directory of navbar in registrar/index.php

May mga fixes lang ulit sa registrar at navbar ng registrar

---

student/academic/TCPDF/config/tcpdf_config.php
student/academic/editmodal-ce.php
student/academic/editmodal-ga.php
student/academic/editmodal-me.php
student/academic/editmodal-so.php
student/academic/generatepdf_ce.php
student/academic/generatepdf_so.php

updated editmodal and pdf

---

student/registrar.php
student/registrar/FAQ.php
student/registrar/create_request.php
student/registrar/trans_tables/delete.php
student/registrar/trans_tables/delete_row.php
student/registrar/trans_tables/edit.php
student/registrar/trans_tables/edit_row.php
student/registrar/trans_tables/modal_view.php
student/registrar/trans_tables/view_row.php
student/registrar/your_transaction.php
student/transaction_tables/fetch_registrar_request.php
student/transaction_tables/registrar_request_table.php
student/transactions.php

changed faq to help, fixed some reg issues, add reg transaction to My Transactions (for viewing onli)

fixed help, some issues, add transactions

---

student/registrar/create_request.php
student/registrar/trans_tables/delete_row.php
student/registrar/trans_tables/edit_row.php
student/registrar/trans_tables/search.php
student/registrar/trans_tables/view_row.php
student/registrar/your_transaction.php

finalized reg student (as of now)

changed table style, view search, and generating registrar code

---

otms_db.sql
student/conn.php
student/survey.php

-connected survey to database
-added acad_survey sql

updated survey

---

admin/accounting.php
admin/tables/accounting/fetch_payments.php
admin/tables/accounting/payments_table.php
client/accounting.php
client/accounting/payment1.php
client/accounting/payment2.php
client/transaction_tables/fetch_payments.php
client/transaction_tables/payments_table.php
client/transactions.php
student/accounting.php
student/transaction_tables/fetch_payments.php
student/transaction_tables/payments_table.php
student/transactions.php

- Updated Accounting Office Student and client
- Included ulit Transaction History
- Updated Accounting Office Admin

- Updated Payments (Student & Client)

---

admin/academic.php
otms_db.sql
student/academic/cross_enrollment.php
student/academic/grade_accreditation.php
student/academic/manual_enrollment.php
student/academic/shifting.php
student/academic/subject_overload.php

Added a choice in Status/admin
Added a "Note" in Row/admin &student
Updated otms_db

Updated academic admin and student

---

admin/tables/registrar/doc_requests.php
admin/tables/registrar/fetch_doc_requests.php
client/registrar/create_request.php
client/registrar/submit_request.php
student/registrar/create_request.php

Reason for Requesting Modal Function (Registrar Student and Client Side)

Reason for Requesting Modal Function

---

student/accounting/css/payment2.css
student/accounting/payment2.php

Redesign of Accounting Payment Voucher

---

student/accounting/css/payment2.css
student/accounting/payment2.php

Exp Date added to Accounting Payment Voucher

---

client/transaction_tables/appointment_facility_table.php
client/transaction_tables/cancel_equipment.php
client/transaction_tables/cancel_facility.php
client/transaction_tables/request_equipment_table.php
otms_db new.sql
student/transaction_tables/appointment_facility_table.php
student/transaction_tables/cancel_equipment.php
student/transaction_tables/cancel_facility.php
student/transaction_tables/request_equipment_table.php

Added Cancelled Status to statuses table
Added Cancel Button to Equipment request and Facility appointment

Updated Student/Client Side for Admin Office w/ new DB file

---

client/transaction_tables/appointment_facility_table.php
client/transaction_tables/request_equipment_table.php
student/transaction_tables/appointment_facility_table.php
student/transaction_tables/request_equipment_table.php

Disable the cancel button for certain statuses on equipment and facility request

Added disable for cancel button on requests

---

document_types.sql
otms_db.sql
student/accounting/payment1.php

Update sa Accounting Office payment1.php plus nagdagdag me new table document_types for payment1.php

New Accounting Payment1.php + document_types table

---

student/transactions.php

added a funtional button in transaction

cancel button

---

student/accounting/payment1.php

Modified Document type button in payment1.php

---

admin/tables/registrar/update_doc_requests.php

Notification For All Status Function (Registrar)

---

admin/tables/registrar/delete_request.php
admin/tables/registrar/doc_requests.php

- Create README.md
- Update README.md
- Update README.md
- Request Letter change 'Campus' to 'Branch'
- prettier format, change reasonText validation to not allow special characters
- added same validation with student, change calendar to flatpickr
- fixed submit modal and date not being recognized as empty
- fixed all calendars, still has some issues with color formatting of input validation on both student and client
- allow also period, comma and exclamation point
- allow also period, comma and exclamation point
- added delete button and delete request functionality, modified change reason button color

Delete Button and Delete Functionality on Registrar Admin

---

admin/tables/registrar/doc_requests.php
admin/tables/registrar/edit_amount_to_pay.php

- added confirm delete record for rejected and released - modal
- added edit amount modal, and process for editing amount
- fix tooltip not hiding when modal dismiss
- fixed bug on validation

Registrar admin: Edit amount to pay

---

admin/tables/registrar/doc_requests.php
admin/tables/registrar/edit_amount_to_pay.php

- added confirm delete record for rejected and released - modal
- added edit amount modal, and process for editing amount
- fix tooltip not hiding when modal dismiss
- fixed bug on validation
- created confirm amount modal, only allow edit amount of payment to some status,decimal numbers is also now reflected

bug resolved from previous enhancement admin registrar
